spring.config.import=optional:file:.env[.properties]
spring.application.name=govnotify-backend

# ============================================
# DATABASE (MySQL)
# ============================================
# DATABASE
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/govnotify?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD}

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================================
# SERVER
# ============================================
server.port=${PORT:8080}

# ============================================
# EMAIL (Gmail SMTP)
# ============================================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================
# GROQ AI
# ============================================
GROQ_CHATBOT_KEY=${GROQ_KEY}